/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Histoire21LieuxEmblematiquesYaoundeRouteImport } from './routes/histoire.21-lieux-emblematiques-yaounde'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Histoire21LieuxEmblematiquesYaoundeRoute =
  Histoire21LieuxEmblematiquesYaoundeRouteImport.update({
    id: '/histoire/21-lieux-emblematiques-yaounde',
    path: '/histoire/21-lieux-emblematiques-yaounde',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/histoire/21-lieux-emblematiques-yaounde': typeof Histoire21LieuxEmblematiquesYaoundeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/histoire/21-lieux-emblematiques-yaounde': typeof Histoire21LieuxEmblematiquesYaoundeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/histoire/21-lieux-emblematiques-yaounde': typeof Histoire21LieuxEmblematiquesYaoundeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/histoire/21-lieux-emblematiques-yaounde'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/histoire/21-lieux-emblematiques-yaounde'
  id: '__root__' | '/' | '/histoire/21-lieux-emblematiques-yaounde'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Histoire21LieuxEmblematiquesYaoundeRoute: typeof Histoire21LieuxEmblematiquesYaoundeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histoire/21-lieux-emblematiques-yaounde': {
      id: '/histoire/21-lieux-emblematiques-yaounde'
      path: '/histoire/21-lieux-emblematiques-yaounde'
      fullPath: '/histoire/21-lieux-emblematiques-yaounde'
      preLoaderRoute: typeof Histoire21LieuxEmblematiquesYaoundeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Histoire21LieuxEmblematiquesYaoundeRoute:
    Histoire21LieuxEmblematiquesYaoundeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
